### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Kierkenstein** [DoubleV37/ft_transcendence#41]
- [x] - Delete avatar button 
- [x] - Change tournament name form
- [x] - Put back the default picture after using the "Delete" button
- [x] - delete: Resolve bug when delete default.png
- [x] - delete: Do merge with dev

**Comment by ji2myji2my** [comment]
Todo: Delete unused html files in Auth

**Comment by ji2myji2my** [comment]
'Delete button' on the settings_feature branch done. I'm waiting before submitting a pull request because of an upcoming conflict with the 2fa functionality.
