### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by Kierkenstein** [DoubleV37/ft_transcendence#43]
- [x] Full CSS not loading on first access
- [x] Double footer loading on first access

**Comment by Kierkenstein** [comment]
Double footer loading on first access --> Fix en sortant l'include du footer du <body>

**Comment by Kierkenstein** [comment]
Full CSS not loading on first access --> Fix en utilisant une méthode plus simple pour cacher le texte en trop

**Comment by Kierkenstein** [comment]
Les fix ne fonctionnent pas en fait... 
Avant j'avais le problème après chaque logout. 
Maintenant la page ne se load pas correctement la première fois après un "make fre"  OU un logout + suppression totale du cache.

Donc reste toujours à régler :
 
- [ ] Full CSS not loading on first access
- [ ] Double footer loading on first access

Pensez à bien pull front_user_management avant de chercher le fix.
Bon courage !

**Comment by V0lk7** [comment]
At this url => /auth/settings/
CSS is working well, no problem on me.
Double footer solved. A </div> was missing in the "Settings.html". Because of this, the footer has been include in the  <div id="content"> ...

**Comment by Kierkenstein** [comment]
Fixed CSS by overriding the inherited properties of the Django forms
