### ISSUE TITLE
feature/Dashboard/Master

### ISSUE THREAD

**Issue by ji2myji2my** [DoubleV37/ft_transcendence#52]
### Complex branch git:
![image](https://github.com/DoubleV37/ft_transcendence/assets/116174119/b2a628b1-ba76-4962-99d7-f5ad5d2bb431)

- [x] #74
- [x] #75
- [ ] Testing/Bugs
- [ ] Merging to Game

**Comment by Cmasserann** [comment]
score 
max
bounce
max exchange

**Comment by ji2myji2my** [comment]
Bug found. It was caused by an unmanaged merge conflict.
The IA name was changed to IA-Ochen and this change was not made.

**Comment by ji2myji2my** [comment]
Bug modal 2fa: @V0lk7 
Inside this fork and its associate sub-forks, a bug was detected. The bug concerns 2fa feature. 

![Pasted image 20240503083135](https://github.com/DoubleV37/ft_transcendence/assets/116174119/aa3e0d7c-b466-4293-8f67-61ecb5813e8d)
![Pasted image 20240503083322](https://github.com/DoubleV37/ft_transcendence/assets/116174119/1e4d6a72-bb3b-4086-a273-4022023cc409)

**Comment by ji2myji2my** [comment]
Dashboard
- [ ] stats global a peupler 
- [ ] list de game custom a peupler 
- [ ] ecran de matchmacking en tournois a peupler 
- [ ] stat of canava a peupler 
- [ ] page tournoi a terminer
