### ISSUE TITLE
Meeting/Testing_Process

### ISSUE THREAD

**Issue by ji2myji2my** [DoubleV37/ft_transcendence#70]
### **Goal:**

- A quick chat about previous production tests.
- Where we are today.
- And setting up a test process for the rest to make the project easier and more secure.

- [ ] Find a date
- [ ] Find a process
- [ ] Maybe assign a manager

**Comment by ji2myji2my** [comment]
Jimmy date Jeudi

**Comment by Kierkenstein** [comment]
Pourquoi pas demain ? (mercredi)
