### ISSUE TITLE
hotfix/Game/back

### ISSUE THREAD

**Issue by Kierkenstein** [DoubleV37/ft_transcendence#87]
Actuellement la vitesse du jeu depend de la puissance de calcul du PC qui fait tourner le serveur et non d'une boucle de temps.

A faire :

- [x] Baser les appels de fonction de la boucle runGame sur le calcul du Delta Time en lui donnant un frame rate.
- [x] Dans les fonctions de mouvement, ajuster les positions en fonction de ce Delta Time.
- [x] Utiliser le delta time pour les calculs de physique.

PS: Je ne suis pas certain pour les deux derniers elements, c'est peut etre possible de s'en sortir en faisant juste la premiere etape sans changer le contenu des fonctions... a voir.

Tuto donne par Thibault (en JS mais la logique est la meme) : https://jakesgordon.com/writing/javascript-game-foundations-the-game-loop/

**Comment by Cmasserann** [comment]
Alright! I found a solution that isn't from the tutorial, but it works so I'll leave it like that. I can't figure out another way to do it, so it's frustrating. It's probably because of the Mercury's retrograde influence on the moon; it's messing with my mind.
