### ISSUE TITLE
Authentification, utilisateurs

### ISSUE THREAD

**Issue by DoubleV37** [DoubleV37/ft_transcendence#9]
- [x] Système d'authentification (BdD)
- [x] Sign In
- [x] Sign Up
- [ ] Recovery Password
- [ ] Distant Auth with 42 API - OAUTH 2.0
- [x] JWT and 2FA Auth
- [x] Gestion Utilisateur (page compte)

**Comment by V0lk7** [comment]
### OAuth 2.0 - 42 API

- [Django toolkit OAuth](https://django-oauth-toolkit.readthedocs.io/en/latest/)
- [42 Api OAuth](https://api.intra.42.fr/apidoc) / look if Javascript SDK exist for it

### Two-Factor Authentication (2FA)

- [Django toolkit](https://django-two-factor-auth.readthedocs.io/en/1.15.5/)
- enhance the front and the back to be able to login with username/password/2FA code and OAuth/2FA code

### JSON Web token (JWT)

- [Django Toolkit](https://django-rest-framework-simplejwt.readthedocs.io/en/latest/)
- enhance the front to be able to put the token in the request header and to handle the lifespan of it and refresh it when needed.
